name: instagram_profile_app
description: A Flutter app to display Instagram profile details
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.1.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/virat_kohli.png